FactoryBot.define do
  factory :school do
    name { "#{FFaker::Education.school_name} w #{FFaker::AddressPL.city}" }
    city { FFaker::AddressPL.city }
    country { 'PL' }
    slug { name.parameterize }
    logo { nil }
    # join_token is auto-generated by before_create callback
    # Format: xxxx-xxxx-xxxxxxxxxxxx (last 3 segments of UUID)
    join_token { SecureRandom.uuid.split('-').last(3).join('-') }
  end
end
