FactoryBot.define do
  factory :school_class do
    school
    name { "#{rand(1..8)}#{('A'..'D').to_a.sample}" }
    year { '2024/2025' }
    qr_token { SecureRandom.uuid }
    metadata { {} }
    # join_token is auto-generated by before_create callback
    # Format: xxxxxxxx-xxxx-xxxx (first 3 segments of UUID)
    join_token { SecureRandom.uuid.split('-').first(3).join('-') }
  end
end
