require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-i18n
  - rubocop-performance
  - rubocop-factory_bot

I18n/GetText/DecorateFunctionMessage:
  Exclude:
    - "app/policies/**.rb"

I18n/GetText/DecorateString:
  Exclude:
    - db/**/**/*.rb
    - 'lib/tasks/*.rake'
    - 'app/controllers/admin/resources_controller.rb'
    - 'app/interactors/api/v1/management/show_administration.rb'
    - 'app/interactors/api/v1/management/update_administration.rb'

I18n/RailsI18n/DecorateString:
  Enabled: false

Layout/EmptyLines:
  Exclude:
    - 'db/seeds/**/*.rb'
    - 'spec/requests/api/v1/management/students_spec.rb'

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'spec/requests/api/v1/management/students_spec.rb'

Layout/IndentationConsistency:
  Exclude:
    - 'spec/requests/api/v1/management/students_spec.rb'

Layout/TrailingWhitespace:
  Exclude:
    - 'spec/requests/api/v1/management/students_spec.rb'

Layout/LineLength:
  Exclude:
    - "config/initializers/*.rb"
    - 'db/seeds/**/*.rb'

Lint/DuplicateHashKey:
  Exclude:
    - 'db/seeds/**/*.rb'

Lint/UnreachableCode:
  Exclude:
    - 'db/seeds/development/070_subjects_units_modules_contents.rb'

Lint/UnusedMethodArgument:
  Exclude:
    - "app/uploaders/*.rb"

Lint/UselessAssignment:
  Exclude:
    - "db/seeds/**/*.rb"

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
    - "config/**/*.rb"
    - "db/**/*.rb"
    - "lib/tasks/*.rake"
    - "app/serializers/subject_complete_serializer.rb"
    - "app/serializers/parent_serializer.rb"

Metrics/ClassLength:
  Exclude:
    - "app/controllers/admin/resources_controller.rb"
    - "app/interactors/api/v1/management/create_class.rb"
    - "app/interactors/api/v1/management/update_class.rb"
    - "app/interactors/api/v1/management/update_administration.rb"
    - "app/interactors/api/v1/management/create_parent.rb"
    - "app/interactors/api/v1/management/update_parent.rb"
    - "app/interactors/api/v1/management/create_student.rb"

Metrics/CyclomaticComplexity:
  Max: 8
  Exclude:
    - "app/interactors/api/v1/events/list_events.rb"
    - "app/controllers/admin/resources_controller.rb"
    - "app/controllers/concerns/handle_status_code.rb"
    - "app/interactors/api/v1/management/create_parent.rb"
    - "app/interactors/api/v1/management/update_parent.rb"

Metrics/MethodLength:
  Max: 15
  Exclude:
    - "db/**/*.rb"
    - "app/interactors/api/v1/events/list_events.rb"
    - 'app/interactors/api/v1/management/approve_teacher.rb'
    - 'app/interactors/api/v1/management/create_class.rb'
    - 'app/interactors/api/v1/management/update_class.rb'
    - 'app/interactors/api/v1/management/archive_year.rb'
    - 'app/controllers/api/v1/users/registrations_controller.rb'
    - 'app/controllers/api/v1/management/notifications_controller.rb'
    - 'app/controllers/management/notifications_controller.rb'
    - 'app/controllers/management/dashboard_controller.rb'
    - 'app/services/notification_service.rb'
    - 'app/controllers/admin/resources_controller.rb'
    - 'app/interactors/api/v1/contents/show_content.rb'
    - 'app/interactors/api/v1/learning_modules/show_learning_module.rb'
    - 'app/controllers/admin/notifications_controller.rb'
    - 'app/interactors/api/v1/management/list_administrations.rb'
    - 'app/interactors/api/v1/management/show_administration.rb'
    - 'app/interactors/api/v1/management/update_administration.rb'
    - 'app/controllers/concerns/handle_status_code.rb'
    - 'app/interactors/api/v1/management/create_parent.rb'
    - 'app/interactors/api/v1/management/update_parent.rb'
    - 'app/interactors/api/v1/management/list_parents.rb'

Metrics/PerceivedComplexity:
  Max: 8
  Exclude:
    - "app/controllers/admin/resources_controller.rb"
    - "app/controllers/concerns/handle_status_code.rb"
    - "app/interactors/api/v1/management/create_parent.rb"
    - "app/interactors/api/v1/management/update_parent.rb"

Metrics/BlockNesting:
  Max: 3
  Exclude:
    - "app/controllers/admin/resources_controller.rb"

Naming/MethodName:
  Exclude:
    - "lib/**/*.rb"

Rails/NotNullColumn:
  Exclude:
    - "db/migrate/*.rb"

Rails/Output:
  Exclude:
    - "db/seeds.rb"

Rails/SkipsModelValidations:
  Exclude:
    - "app/models/project.rb"
    - "db/seeds/**/*.rb"
    - "spec/**/*.rb" # update_column is intentionally used in tests to simulate edge cases

RSpec/EmptyExampleGroup:
  Exclude:
    - "spec/**/*.rb"

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 7 # Some tests legitimately need more expectations to verify complex behavior

RSpec/MultipleMemoizedHelpers:
  Max: 12
  Exclude:
    - 'spec/requests/api/v1/contents_spec.rb'

RSpec/ScatteredSetup:
  Exclude:
    - 'spec/requests/api/v1/management/students_spec.rb'
    - 'spec/requests/api/v1/management/academic_years_spec.rb'
    - 'spec/requests/api/v1/subjects_spec.rb'
    - 'spec/requests/api/v1/units_spec.rb'
    - 'spec/requests/api/v1/contents_spec.rb'
    - 'spec/requests/api/v1/management/administrations_spec.rb'
    - 'spec/requests/api/v1/management/parents_spec.rb'

RSpec/NestedGroups:
  Max: 4

RSpec/RepeatedExampleGroupDescription:
  Exclude:
    - "spec/**/*.rb"

RSpec/VariableName:
  Exclude:
    - "spec/**/*.rb"

Naming/VariableNumber:
  Exclude:
    - 'spec/**/*.rb' # Variable names like class_2024 are clear and readable in tests

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false