require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-i18n
  - rubocop-performance
  - rubocop-factory_bot

I18n/GetText/DecorateFunctionMessage:
  Exclude:
    - "app/policies/**.rb"

I18n/GetText/DecorateString:
  Exclude:
    - db/**/**/*.rb
    - 'lib/tasks/*.rake'

I18n/RailsI18n/DecorateString:
  Enabled: false

Layout/EmptyLines:
  Exclude:
    - 'db/seeds/**/*.rb'

Layout/LineLength:
  Exclude:
    - "config/initializers/*.rb"
    - 'db/seeds/**/*.rb'

Lint/DuplicateHashKey:
  Exclude:
    - 'db/seeds/**/*.rb'

Lint/UnusedMethodArgument:
  Exclude:
    - "app/uploaders/*.rb"

Lint/UselessAssignment:
  Exclude:
    - "db/seeds/**/*.rb"

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
    - "config/**/*.rb"
    - "db/**/*.rb"
    - "lib/tasks/*.rake"

Metrics/ClassLength:
  Exclude:
    - "app/controllers/admin/resources_controller.rb"

Metrics/CyclomaticComplexity:
  Max: 8
  Exclude:
    - "app/interactors/api/v1/events/list_events.rb"

Metrics/MethodLength:
  Max: 15
  Exclude:
    - "db/**/*.rb"
    - "app/interactors/api/v1/events/list_events.rb"
    - 'app/interactors/api/v1/management/approve_teacher.rb'
    - 'app/controllers/api/v1/users/registrations_controller.rb'
    - 'app/controllers/api/v1/management/notifications_controller.rb'
    - 'app/controllers/management/notifications_controller.rb'
    - 'app/controllers/management/dashboard_controller.rb'
    - 'app/services/notification_service.rb'

Naming/MethodName:
  Exclude:
    - "lib/**/*.rb"

Rails/NotNullColumn:
  Exclude:
    - "db/migrate/*.rb"

Rails/Output:
  Exclude:
    - "db/seeds.rb"

Rails/SkipsModelValidations:
  Exclude:
    - "app/models/project.rb"
    - "db/seeds/**/*.rb"

RSpec/EmptyExampleGroup:
  Exclude:
    - "spec/**/*.rb"

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 4

RSpec/RepeatedExampleGroupDescription:
  Exclude:
    - "spec/**/*.rb"

RSpec/VariableName:
  Exclude:
    - "spec/**/*.rb"

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false