require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-i18n
  - rubocop-performance
  - rubocop-factory_bot

I18n/GetText/DecorateFunctionMessage:
  Exclude:
    - "app/policies/**.rb"

I18n/GetText/DecorateString:
  Exclude:
    - db/**/**/*.rb
    - 'lib/tasks/*.rake'
    - 'app/controllers/admin/resources_controller.rb'
    - 'app/controllers/register/wizard_controller.rb'
    - 'app/controllers/api/v1/student/**/*.rb'
    - 'app/interactors/api/v1/management/show_administration.rb'
    - 'app/interactors/api/v1/management/update_administration.rb'
    - 'app/services/notification_service.rb'
    - 'spec/**/*.rb'

I18n/RailsI18n/DecorateString:
  Enabled: false

Layout/EmptyLines:
  Exclude:
    - 'db/seeds/**/*.rb'
    - 'spec/requests/api/v1/management/students_spec.rb'

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'spec/requests/api/v1/management/students_spec.rb'

Layout/IndentationConsistency:
  Exclude:
    - 'spec/requests/api/v1/management/students_spec.rb'

Layout/TrailingWhitespace:
  Exclude:
    - 'spec/requests/api/v1/management/students_spec.rb'

Layout/LineLength:
  Exclude:
    - "config/initializers/*.rb"
    - 'db/seeds/**/*.rb'

Lint/DuplicateHashKey:
  Exclude:
    - 'db/seeds/**/*.rb'

Lint/UnreachableCode:
  Exclude:
    - 'db/seeds/development/070_subjects_units_modules_contents.rb'

Lint/UnusedMethodArgument:
  Exclude:
    - "app/uploaders/*.rb"

Lint/UselessAssignment:
  Exclude:
    - "db/seeds/**/*.rb"

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
    - "config/**/*.rb"
    - "db/**/*.rb"
    - "lib/tasks/*.rake"
    - "app/serializers/subject_complete_serializer.rb"
    - "app/serializers/parent_serializer.rb"
    - "app/controllers/dashboard_controller.rb"

Metrics/ClassLength:
  Exclude:
    - "app/controllers/admin/resources_controller.rb"
    - "app/controllers/dashboard_controller.rb"
    - "app/controllers/api/v1/teacher/dashboard_controller.rb"
    - "app/controllers/api/v1/student/dashboard_controller.rb"
    - "app/controllers/register/wizard_controller.rb"
    - "app/interactors/api/v1/management/create_class.rb"
    - "app/interactors/api/v1/management/update_class.rb"
    - "app/interactors/api/v1/management/update_administration.rb"
    - "app/interactors/api/v1/management/create_parent.rb"
    - "app/interactors/api/v1/management/update_parent.rb"
    - "app/interactors/api/v1/management/create_student.rb"
    - "app/interactors/api/v1/management/approve_student.rb"
    - "app/interactors/api/v1/management/approve_teacher.rb"
    - "app/interactors/api/v1/management/destroy_student.rb"
    - "app/interactors/register/set_pin_confirm_submit.rb"
    - "app/services/notification_service.rb"
    - "app/controllers/application_controller.rb"
    - "app/controllers/users/sessions_controller.rb"

Metrics/CyclomaticComplexity:
  Max: 8
  Exclude:
    - "db/migrate/*.rb" # Migrations can have complex logic for schema changes
    - "app/interactors/api/v1/events/list_events.rb"
    - "app/controllers/admin/resources_controller.rb"
    - "app/controllers/dashboard_controller.rb"
    - "app/controllers/concerns/handle_status_code.rb"
    - "app/interactors/api/v1/management/create_parent.rb"
    - "app/interactors/api/v1/management/update_parent.rb"
    - "app/controllers/application_controller.rb"
    - "app/controllers/users/sessions_controller.rb"
    - "app/controllers/api/v1/student/events_controller.rb"
    - "app/controllers/api/v1/student/quiz_results_controller.rb"

Metrics/MethodLength:
  Max: 15
  Exclude:
    - "db/**/*.rb"
    - "app/interactors/api/v1/events/list_events.rb"
    - 'app/interactors/api/v1/management/approve_teacher.rb'
    - 'app/interactors/api/v1/management/approve_student.rb'
    - 'app/interactors/api/v1/management/create_class.rb'
    - 'app/interactors/api/v1/management/update_class.rb'
    - 'app/interactors/api/v1/management/archive_year.rb'
    - 'app/interactors/api/v1/management/destroy_teacher.rb'
    - 'app/controllers/api/v1/users/registrations_controller.rb'
    - 'app/controllers/api/v1/management/notifications_controller.rb'
    - 'app/controllers/management/notifications_controller.rb'
    - 'app/controllers/management/dashboard_controller.rb'
    - 'app/controllers/dashboard_controller.rb'
    - 'app/controllers/register/wizard_controller.rb'
    - 'app/controllers/teacher_registration_controller.rb'
    - 'app/services/notification_service.rb'
    - 'app/controllers/admin/resources_controller.rb'
    - 'app/interactors/api/v1/contents/show_content.rb'
    - 'app/interactors/api/v1/learning_modules/show_learning_module.rb'
    - 'app/controllers/admin/notifications_controller.rb'
    - 'app/interactors/api/v1/management/list_administrations.rb'
    - 'app/interactors/api/v1/management/show_administration.rb'
    - 'app/interactors/api/v1/management/update_administration.rb'
    - 'app/controllers/concerns/handle_status_code.rb'
    - 'app/interactors/api/v1/management/create_parent.rb'
    - 'app/interactors/api/v1/management/update_parent.rb'
    - 'app/interactors/api/v1/management/list_parents.rb'
    - 'app/controllers/api/v1/teacher/dashboard_controller.rb'
    - 'app/controllers/home_controller.rb'
    - 'app/controllers/users/sessions_controller.rb'
    - 'app/controllers/student_dashboard_controller.rb'
    - 'app/interactors/register/set_pin_confirm_submit.rb'
    - 'app/interactors/register/create_teacher_after_verify.rb'
    - 'app/interactors/register/teacher_profile_submit.rb'
    - 'app/controllers/api/v1/student/dashboard_controller.rb'
    - 'app/controllers/api/v1/student/events_controller.rb'
    - 'app/controllers/api/v1/student/quiz_results_controller.rb'

Metrics/PerceivedComplexity:
  Max: 8
  Exclude:
    - "db/migrate/*.rb" # Migrations can have complex logic for schema changes
    - "app/controllers/admin/resources_controller.rb"
    - "app/controllers/dashboard_controller.rb"
    - "app/controllers/api/v1/teacher/dashboard_controller.rb"
    - "app/controllers/concerns/handle_status_code.rb"
    - "app/helpers/dashboard_helper.rb"
    - "app/interactors/api/v1/management/create_parent.rb"
    - "app/interactors/api/v1/management/update_parent.rb"
    - "app/interactors/api/v1/management/approve_teacher.rb"
    - "app/interactors/register/create_teacher_after_verify.rb"
    - "app/controllers/application_controller.rb"
    - "app/controllers/users/sessions_controller.rb"
    - "app/controllers/api/v1/student/events_controller.rb"
    - "app/controllers/api/v1/student/quiz_results_controller.rb"

Metrics/BlockNesting:
  Max: 3
  Exclude:
    - "app/controllers/admin/resources_controller.rb"

Naming/MethodName:
  Exclude:
    - "lib/**/*.rb"

Rails/DynamicFindBy:
  Exclude:
    - "spec/models/school_join_token_spec.rb"
    - "spec/models/school_class_join_token_spec.rb"
    - "app/controllers/api/v1/student/enrollments_controller.rb"

Rails/NotNullColumn:
  Exclude:
    - "db/migrate/*.rb"

Rails/Output:
  Exclude:
    - "db/seeds.rb"

Rails/SkipsModelValidations:
  Exclude:
    - "app/models/project.rb"
    - "db/seeds/**/*.rb"
    - "db/migrate/*.rb" # update_column is intentionally used in migrations to avoid callbacks
    - "lib/tasks/*.rake" # update_column is intentionally used in rake tasks to avoid callbacks
    - "spec/**/*.rb" # update_column is intentionally used in tests to simulate edge cases
    - "app/interactors/api/v1/management/destroy_student.rb" # Intentional: clearing school_id without triggering callbacks
    - "app/interactors/api/v1/management/destroy_teacher.rb" # Intentional: clearing school_id without triggering callbacks

Rails/HelperInstanceVariable:
  Exclude:
    - "app/helpers/dashboard_helper.rb"

RSpec/EmptyExampleGroup:
  Exclude:
    - "spec/**/*.rb"

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 8 # Some tests legitimately need more expectations to verify complex behavior

RSpec/MultipleMemoizedHelpers:
  Max: 12
  Exclude:
    - 'spec/requests/api/v1/contents_spec.rb'
    - 'spec/requests/api/v1/student/**/*.rb'

RSpec/ScatteredSetup:
  Exclude:
    - 'spec/requests/api/v1/management/students_spec.rb'
    - 'spec/requests/api/v1/management/academic_years_spec.rb'
    - 'spec/requests/api/v1/subjects_spec.rb'
    - 'spec/requests/api/v1/units_spec.rb'
    - 'spec/requests/api/v1/contents_spec.rb'
    - 'spec/requests/api/v1/management/administrations_spec.rb'
    - 'spec/requests/api/v1/management/parents_spec.rb'
    - 'spec/requests/api/v1/student/**/*.rb'

RSpec/LetSetup:
  Exclude:
    - 'spec/controllers/dashboard_controller_spec.rb'
    - 'spec/requests/management/controllers_spec.rb'
    - 'spec/interactors/api/v1/management/approve_teacher_spec.rb'
    - 'spec/interactors/api/v1/management/destroy_teacher_spec.rb'
    - 'spec/interactors/register/create_teacher_after_verify_spec.rb'
    - 'spec/requests/api/v1/student/**/*.rb'

RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/controllers/application_controller_spec.rb'
    - 'spec/interactors/base_interactor_spec.rb'
    - 'spec/interactors/api/v1/register/register_steps_spec.rb'
    - 'spec/policies/application_policy_spec.rb'
    - 'spec/controllers/admin/sessions_controller_spec.rb'
    - 'spec/requests/after_sign_in_redirect_spec.rb'

RSpec/MessageSpies:
  Exclude:
    - 'spec/controllers/application_controller_spec.rb'

RSpec/RepeatedExampleGroupBody:
  Exclude:
    - 'spec/controllers/application_controller_spec.rb'

RSpec/AnyInstance:
  Exclude:
    - 'spec/interactors/api/v1/management/approve_student_spec.rb'
    - 'spec/interactors/api/v1/management/destroy_student_spec.rb'

RSpec/NestedGroups:
  Max: 4

RSpec/RepeatedExampleGroupDescription:
  Exclude:
    - "spec/**/*.rb"

RSpec/DescribeClass:
  Exclude:
    - 'spec/interactors/api/v1/headmasters/headmasters_spec.rb'
    - 'spec/interactors/api/v1/learning_modules/learning_modules_spec.rb'
    - 'spec/interactors/api/v1/register/register_steps_spec.rb'
    - 'spec/interactors/api/v1/schools/schools_spec.rb'
    - 'spec/interactors/api/v1/students/students_spec.rb'
    - 'spec/interactors/api/v1/subjects/subjects_spec.rb'
    - 'spec/interactors/api/v1/teachers/teachers_spec.rb'
    - 'spec/interactors/api/v1/units/units_spec.rb'

RSpec/DescribeMethod:
  Exclude:
    - 'spec/controllers/check_user_active_spec.rb'
    - 'spec/models/school_class_join_token_spec.rb'
    - 'spec/models/school_join_token_spec.rb'
    - 'spec/models/user_active_status_spec.rb'
    - 'spec/services/notification_service_enrollment_spec.rb'

RSpec/SpecFilePathFormat:
  Exclude:
    - 'spec/controllers/check_user_active_spec.rb'
    - 'spec/services/notification_service_enrollment_spec.rb'

RSpec/VariableName:
  Exclude:
    - "spec/**/*.rb"

Naming/VariableNumber:
  Exclude:
    - 'spec/**/*.rb' # Variable names like class_2024 are clear and readable in tests

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false