# frozen_string_literal: true

return if School.exists?

log('Create Schools...')
# NOTE: join_token is auto-generated by before_create callback
# Format: xxxx-xxxx-xxxxxxxxxxxx (last 3 segments of UUID)

gis_logo  = Rails.root.join('db/files/schools/gis.png')
sp18_logo = Rails.root.join('db/files/schools/sp18.png')
sp35_logo = Rails.root.join('db/files/schools/sp35.jpg')
sp51_logo = Rails.root.join('db/files/schools/sp51.jpg')
default_logo = Rails.root.join('db/files/schools/default.png')

@school_a = School.new(
  name: 'Szkoła Podstawowa nr 53',
  slug: 'sp53-gdynia',
  address: 'ul. Gen. J. Hallera 9',
  postcode: '81-453',
  city: 'Gdynia',
  phone: '+48 58 622 22 24',
  email: 'sekretariat@zso6.edu.gdynia.pl',
  homepage: 'https://sp53gdynia.pl/'
)
@school_a.logo = uploaded_file(default_logo) if File.exist?(default_logo)
@school_a.save!

@school_b = School.new(
  name: 'Szkoła Podstawowa nr 18',
  slug: 'sp18-gdynia',
  address: 'ul. Krasickiego 28',
  postcode: '81-385',
  city: 'Gdynia',
  phone: '+48 58 620 69 43',
  email: 'sekretariat@sp18.edu.gdynia.pl',
  homepage: 'https://sp18.gdynia.pl/'
)
@school_b.logo = uploaded_file(sp18_logo) if File.exist?(sp18_logo)
@school_b.save!

@school_c = School.new(
  name: 'Gdynia International School (GIS)',
  slug: 'gis-gdynia',
  address: 'ul. Kapitańska 37',
  postcode: '81-249',
  city: 'Gdynia',
  phone: '+48 782 777 155',
  homepage: 'https://gis.gdynia.pl/'
)
@school_c.logo = uploaded_file(gis_logo) if File.exist?(gis_logo)
@school_c.save!

@school_d = School.new(
  name: 'Szkoła Podstawowa nr 51',
  slug: 'sp51-gdynia',
  address: 'ul. Słowackiego 53',
  postcode: '81-392',
  city: 'Gdynia',
  phone: '+48 725 269 935',
  homepage: 'https://sp51gdynia.pl/'
)
@school_d.logo = uploaded_file(sp51_logo) if File.exist?(sp51_logo)
@school_d.save!

@school_e = School.new(
  name: 'Szkoła Podstawowa nr 35 im. kpt. Stanisława Kosko',
  slug: 'sp35-gdynia',
  address: 'ul. Uczniowska 1',
  postcode: '81-647',
  city: 'Gdynia',
  phone: '+48 58 624 09 74',
  homepage: 'https://www.sp35gdynia.pl/'
)
@school_e.logo = uploaded_file(sp35_logo) if File.exist?(sp35_logo)
@school_e.save!

@school_f = School.new(
  name: 'Szkoła Podstawowa nr 12 im. gen. Mariusza Zaruskiego',
  slug: 'sp12-gdynia',
  address: 'ul. Stawna 4/6',
  postcode: '81-629',
  city: 'Gdynia',
  phone: '+48 58 624 04 07',
  homepage: 'https://sp12gdynia.pl/'
)
@school_f.logo = uploaded_file(default_logo) if File.exist?(default_logo)
@school_f.save!
