# frozen_string_literal: true

return if SchoolClass.exists?

log('Create School Classes...')
# NOTE: join_token is auto-generated by before_create callback
# Format: xxxxxxxx-xxxx-xxxx (first 3 segments of UUID)

year = '2025/2026'

# School A (SP53) - Classes from website or default list
sp53_classes = %w[4A 4B 4N 5A 5N 6 7A 7B 8A 8B 8C 8N]
sp53_classes.each do |class_name|
  SchoolClass.create!(
    school: @school_a,
    name: class_name,
    year: year,
    qr_token: SecureRandom.uuid,
    metadata: { profile: 'ogólny' }
  )
end

# School B (SP18) - Classes (using same default list)
sp18_classes = %w[4A 4B 4N 5A 5N 6 7A 7B 8A 8B 8C 8N]
sp18_classes.each do |class_name|
  SchoolClass.create!(
    school: @school_b,
    name: class_name,
    year: year,
    qr_token: SecureRandom.uuid,
    metadata: { profile: 'ogólny' }
  )
end

# Store references for use in other seeds
@class_4b = SchoolClass.find_by!(school: @school_a, name: '4B')
@class_5a = SchoolClass.find_by!(school: @school_a, name: '5A')
